### ISSUE TITLE
What is this?

### ISSUE THREAD

**Issue by iocmet** [Fish-Sticks/headhunter#20]
https://github.com/Fish-Sticks/headhunter/blob/master/headhunter/src/main.cpp#L46
(Just want know)

**Comment by Fish-Sticks** [comment]
It's bytecode for a metatable hook on the name-call metamethod. You can use a disassembler if you wanna view what the bytecode means (you might need to mod it since this is luau, but luau does come with an included disassembler). I didn't give out the raw script cause I didn't want skids renaming my credits menu (it shows a credits menu when that is loaded too). So in simple words, a watermark + functionality for scripts that use game:HttpGet (a custom function).

**Comment by Fish-Sticks** [comment]
join the discord and ping a bunch of people and ask there
